# Generated by Django 3.1 on 2020-08-25 10:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('calificacion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('localizacion', models.CharField(max_length=20)),
                ('foto', models.FileField(null=True, upload_to='img/alojamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Aparcamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=30)),
                ('destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Monumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('agno_inniaguracion', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(-10000)])),
                ('historia', models.CharField(max_length=500)),
                ('localizacion', models.CharField(max_length=20)),
                ('precio_pers', models.PositiveIntegerField(default=0, max_length=2)),
                ('precio_disc', models.PositiveIntegerField(default=0, max_length=2)),
                ('foto', models.FileField(null=True, upload_to='img/ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=2)),
                ('password', models.CharField(max_length=30)),
                ('foto', models.FileField(null=True, upload_to='img/usuario')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('comentario', models.CharField(max_length=500)),
                ('monumentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handitour.monumento')),
                ('usuarios', models.ManyToManyField(to='handitour.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('usuarios', models.ManyToManyField(to='handitour.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('localizacion', models.CharField(max_length=30)),
                ('lineas', models.ManyToManyField(to='handitour.Lineas')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('historia', models.CharField(max_length=500)),
                ('localizacion', models.CharField(max_length=20)),
                ('foto', models.FileField(null=True, upload_to='img/ciudad')),
                ('usuarios', models.ManyToManyField(to='handitour.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('historia', models.CharField(max_length=500)),
                ('localizacion', models.CharField(max_length=20)),
                ('foto', models.FileField(null=True, upload_to='img/barrio')),
                ('alojamientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handitour.alojamiento')),
                ('aparcamientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handitour.aparcamiento')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handitour.ciudad')),
                ('paradas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handitour.parada')),
            ],
        ),
    ]
