# Generated by Django 3.1 on 2020-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='historia',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='historia',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monumento',
            name='historia',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='monumento',
            name='precio_disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monumento',
            name='precio_pers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
