# Generated by Django 3.1 on 2020-08-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lineas',
            new_name='Linea',
        ),
    ]
