# Generated by Django 3.1 on 2020-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0002_auto_20200911_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumento',
            name='precio_disc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='monumento',
            name='precio_pers',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
