# Generated by Django 3.1 on 2020-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0002_auto_20200827_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumento',
            name='foto',
            field=models.FileField(null=True, upload_to='img/monumento'),
        ),
    ]
