# Generated by Django 3.1 on 2020-08-25 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0003_auto_20200825_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrio',
            name='alojamientos',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='aparcamientos',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='barrio',
            name='paradas',
        ),
        migrations.RemoveField(
            model_name='parada',
            name='lineas',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ciudades',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='monumentos',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='usuarios',
        ),
        migrations.DeleteModel(
            name='Alojamiento',
        ),
        migrations.DeleteModel(
            name='Aparcamiento',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
        migrations.DeleteModel(
            name='Monumento',
        ),
        migrations.DeleteModel(
            name='Parada',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
