# Generated by Django 3.1 on 2020-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0003_auto_20200827_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumento',
            name='localizacion',
            field=models.CharField(max_length=30),
        ),
    ]
