# Generated by Django 3.1 on 2020-09-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0003_auto_20200912_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handitour.transporte'),
        ),
    ]
