# Generated by Django 3.1 on 2020-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0004_auto_20200828_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='foto',
            field=models.FileField(null=True, upload_to='img/'),
        ),
    ]
