# Generated by Django 3.1 on 2020-09-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0004_linea_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='numero_nombre',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
