# Generated by Django 3.1 on 2020-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0005_linea_numero_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='localizacion',
            field=models.CharField(max_length=100),
        ),
    ]
