# Generated by Django 3.1 on 2020-09-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0006_auto_20200831_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='monumento',
            name='ciudad',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='handitour.ciudad'),
            preserve_default=False,
        ),
    ]
