# Generated by Django 3.1 on 2020-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0006_auto_20200926_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='localizacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aparcamiento',
            name='localizacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='localizacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monumento',
            name='localizacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parada',
            name='localizacion',
            field=models.CharField(max_length=100),
        ),
    ]
