# Generated by Django 3.1 on 2020-09-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0007_monumento_ciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monumento',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='monumentos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='handitour.monumento'),
            preserve_default=False,
        ),
    ]
