# Generated by Django 3.1 on 2020-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0007_auto_20200926_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
    ]
