# Generated by Django 3.1 on 2021-01-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handitour', '0008_auto_20201229_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracion',
            old_name='monumentos',
            new_name='monumento',
        ),
    ]
